

local HelpRenderSystem = Engine.RegisterUIRenderSystem("Help Render");

local boxes = {}

function HelpRenderSystem:ShouldRender(ui)
	return ShowHelpWindow
end

local evenColor = Colors.Yellow
local oddColor = LerpColor(Colors.Yellow, Colors.White, 0.5)
local t = 0

local function TextRow(ui, b, gl, desc)
	ui.Space(1)
	ui.PushOrder("-")
		ui.Label("  " .. gl)
		if b % 2 == 1 then
			ui.PushStyle(evenColor)
		else
			ui.PushStyle(oddColor)
		end
		ui.Label(" " .. string.rep(".", 16 - #desc - #gl) .. desc)
		ui.PopStyle()
	ui.PopOrder()
end

local function GlyphRow(ui, b, gl, desc)
	ui.Space(1)
	ui.PushOrder("-")
		ui.Glyphs({ " ", " ", gl })
		if b % 2 == 1 then
			ui.PushStyle(evenColor)
		else
			ui.PushStyle(oddColor)
		end
		ui.Label(" " .. string.rep(".", 16 - #desc) .. desc)
		ui.PopStyle()
	ui.PopOrder()
end

function HelpRenderSystem.Render(ui)
	local w, h = Dungeon.floor:Size()	
	ui.ClearBox(1, 1, w + 15, h + 5)
	ui.FillRect(1, 1, w + 15, h + 5)

	ui.PushBox(6, 2, 20, 20)
		ui.PushOrder("|")
			ui.Label("[ CONTROLS ]")
			ui.Space(1)
			ui.PushStyle(Colors.White, Colors.DarkMagenta)
			ui.Label("| Movement          ")
			ui.PopStyle()
			TextRow(ui, 1, "ARROWS", "move")
			TextRow(ui, 2, "SHIFT", "jump")
			TextRow(ui, 3, "SPACE", "wait")
			ui.Space(1)
			ui.Space(1)

			ui.PushStyle(Colors.White, Colors.DarkMagenta)
			ui.Label("| Info              ")
			ui.PopStyle()
			TextRow(ui, 1, "hold ALT", "scan")
			TextRow(ui, 2, "TAB", "diary")
			TextRow(ui, 3, "I", "inventory")

			ui.Space(1)
			ui.Space(1)

			ui.PushStyle(Colors.White, Colors.DarkMagenta)
			ui.Label("| Game              ")
			ui.PopStyle()
			TextRow(ui, 1, "F1", "help")
			TextRow(ui, 2, "hold F10", "exit")
			ui.Space(14)

			ui.Label("[ PROPHECY ]")
			ui.Space(1)
			ui.PushOrder("-")
				ui.Label("Grasp for the ")
				ui.PushStyle(Colors.Yellow, Colors.Black)
				ui.Label("GLYPHS")
				ui.PopStyle()
				ui.Label(",")
			ui.PopOrder()
			ui.Space(1)
			ui.PushOrder("-")
				ui.Label(" Find the next ")
				ui.PushStyle(Colors.Red, Colors.Yellow)
				ui.Label("ALTAR")
				ui.PopStyle()
				ui.Label(",")
			ui.PopOrder()
			ui.Space(1)
			ui.PushOrder("-")
				ui.PushStyle(Colors.LightMagenta, Colors.Black)
				ui.Label("TENSION")
				ui.PopStyle()
				ui.Label(" feeds ")
				ui.PushStyle(Colors.Yellow, Colors.Magenta)
				ui.Label("RIFTs")
				ui.PopStyle()
				ui.Label(",")
			ui.PopOrder()
			ui.Space(1)
			ui.PushOrder("-")
				ui.PushStyle(Colors.Yellow, Colors.Magenta)
				ui.Label("RIFTs")
				ui.PopStyle()
				ui.Label(" bring us fear!")
			ui.PopOrder()
			ui.Space(1)
			ui.PushOrder("-")
				ui.PushStyle(Colors.Gray, Colors.Black)
				ui.Label(" ???")
				ui.PopStyle()
				ui.Label(" to get the ")
				ui.PushStyle(Colors.Green, Colors.Black)
				ui.Label("SEAL")
				ui.PopStyle()
				ui.Label(",")
			ui.PopOrder()
			ui.Space(1)
			ui.PushOrder("-")
				ui.PushStyle(Colors.Green, Colors.Black)
				ui.Label("SEAL ")
				ui.PopStyle()
				ui.Label("the ")
				ui.PushStyle(Colors.Black, Colors.Red)
				ui.Label("HATE")
				ui.PopStyle()
				ui.Label(" below.")
			ui.PopOrder()
		ui.PopOrder()
	ui.PopBox()

	
	ui.PushBox(35, 2, 20, 20)
		ui.PushOrder("|")
			ui.Label("[ VISUALS ]")
			ui.Space(1)
			ui.PushStyle(Colors.White, Colors.DarkMagenta)
			ui.Label("| Dungeon           ")
			ui.PopStyle()
			GlyphRow(ui, 1, "player", "person")
			GlyphRow(ui, 2, ".", "floor")
			GlyphRow(ui, 3, "b", "book")
			GlyphRow(ui, 4, "#", "wall")
			GlyphRow(ui, 5, "altar", "altar")
			GlyphRow(ui, 6, "key", "key")
			GlyphRow(ui, 7, "treasure", "gold")
			GlyphRow(ui, 8, "mineral", "mineral")
			GlyphRow(ui, 9, "plant", "plant")
			ui.Space(1)
			ui.Space(1)
			ui.PushStyle(Colors.White, Colors.DarkMagenta)
			ui.Label("| Containers        ")
			ui.PopStyle()
			GlyphRow(ui, 1, "crate", "closed crate")
			GlyphRow(ui, 2, "crate_empty", "empty crate")
			GlyphRow(ui, 3, "chest", "closed chest")
			GlyphRow(ui, 4, "chest_empty", "empty chest")
			ui.Space(1)
			ui.Space(1)
			ui.PushStyle(Colors.White, Colors.DarkMagenta)
			ui.Label("| Set Dressing      ")
			ui.PopStyle()
			GlyphRow(ui, 1, "candle", "candle")
			GlyphRow(ui, 2, "anvil", "anvil")
			GlyphRow(ui, 3, "grate1", "grate")
			GlyphRow(ui, 4, "cauldron", "cauldron")
			GlyphRow(ui, 5, "furnace", "furnace")
			GlyphRow(ui, 6, "table", "table")
			GlyphRow(ui, 7, "shelf", "book shelf")
			GlyphRow(ui, 8, "shelf_empty", "empty shelf")
			ui.Space(1)
			ui.Space(1)
			ui.PushStyle(Colors.White, Colors.DarkMagenta)
			ui.Label("| Elements          ")
			ui.PopStyle()
			GlyphRow(ui, 1, "flame", "flame")
			GlyphRow(ui, 2, "cinders", "cinders")
			GlyphRow(ui, 3, "rift", "rift")
			GlyphRow(ui, 4, "portal", "portal")
			ui.Space(5)

			ui.PushOrder("-")
				ui.Label("       ")
				ui.PushStyle(Colors.Black, Colors.LightMagenta)
				ui.Label("[ESCAPE] Back")
				ui.PopStyle()
			ui.PopOrder()
		ui.PopOrder()
	ui.PopBox()
end
