
Glossary.Meta.Default = FontPresentationMode("whitrabt", 14, true)

Glossary.Default = {
	skel1 = { char = "t", fg = Colors.Gray, bg = Colors.Black },
	skel2 = { char = "t", fg = Colors.White, bg = Colors.Black },

	gob1 = { char = "g", fg = Colors.White, bg = Colors.Black },
	gob2 = { char = "g", fg = Colors.Green, bg = Colors.Black },

	kobold1 = { char = "k", fg = Colors.White, bg = Colors.Black },
	kobold2 = { char = "k", fg = Colors.Red, bg = Colors.Black },

	mage = { char = "@", fg = Colors.Yellow, bg = Colors.Black },
	monk = { char = "@", fg = Colors.Yellow, bg = Colors.Black },

	door_closed = { char = "+", fg = Colors.Gray, bg = Colors.Black },
	door_open = { char = "_", fg = Colors.Gray, bg = Colors.Black },

	back_dark = { char = ".", fg = Colors:Grayscale(20), bg = Colors.Black },
	back_semi = { char = ".", fg = Colors:Grayscale(40), bg = Colors.Black },
	back_mid = { char = ".", fg = Colors:Grayscale(80), bg = Colors.Black },
	back_lit = { char = ".", fg = Colors:Grayscale(100), bg = Colors.Black },

	back_old1 = { char = ".", fg = Colors:Grayscale(10), bg = Colors.Black },
	back_old2 = { char = ".", fg = Colors:Grayscale(15), bg = Colors.Black },
	back_old3 = { char = ".", fg = Colors:Grayscale(20), bg = Colors.Black },

	a = { char = "a", fg = Colors.White, bg = Colors.Black },
	b = { char = "b", fg = Colors.White, bg = Colors.Black },
	c = { char = "c", fg = Colors.White, bg = Colors.Black },
	d = { char = "d", fg = Colors.White, bg = Colors.Black },
	e = { char = "e", fg = Colors.White, bg = Colors.Black },
	f = { char = "f", fg = Colors.White, bg = Colors.Black },
	g = { char = "g", fg = Colors.White, bg = Colors.Black },
	h = { char = "h", fg = Colors.White, bg = Colors.Black },
	i = { char = "i", fg = Colors.White, bg = Colors.Black },
	j = { char = "j", fg = Colors.White, bg = Colors.Black },
	k = { char = "k", fg = Colors.White, bg = Colors.Black },
	l = { char = "l", fg = Colors.White, bg = Colors.Black },
	m = { char = "m", fg = Colors.White, bg = Colors.Black },
	n = { char = "n", fg = Colors.White, bg = Colors.Black },
	o = { char = "o", fg = Colors.White, bg = Colors.Black },
	p = { char = "p", fg = Colors.White, bg = Colors.Black },
	q = { char = "q", fg = Colors.White, bg = Colors.Black },
	r = { char = "r", fg = Colors.White, bg = Colors.Black },
	s = { char = "s", fg = Colors.White, bg = Colors.Black },
	t = { char = "t", fg = Colors.White, bg = Colors.Black },
	u = { char = "u", fg = Colors.White, bg = Colors.Black },
	v = { char = "v", fg = Colors.White, bg = Colors.Black },
	w = { char = "w", fg = Colors.White, bg = Colors.Black },
	x = { char = "x", fg = Colors.White, bg = Colors.Black },
	y = { char = "y", fg = Colors.White, bg = Colors.Black },
	z = { char = "z", fg = Colors.White, bg = Colors.Black },
	A = { char = "A", fg = Colors.White, bg = Colors.Black },
	B = { char = "B", fg = Colors.White, bg = Colors.Black },
	C = { char = "C", fg = Colors.White, bg = Colors.Black },
	D = { char = "D", fg = Colors.White, bg = Colors.Black },
	E = { char = "E", fg = Colors.White, bg = Colors.Black },
	F = { char = "F", fg = Colors.White, bg = Colors.Black },
	G = { char = "G", fg = Colors.White, bg = Colors.Black },
	H = { char = "H", fg = Colors.White, bg = Colors.Black },
	I = { char = "I", fg = Colors.White, bg = Colors.Black },
	J = { char = "J", fg = Colors.White, bg = Colors.Black },
	K = { char = "K", fg = Colors.White, bg = Colors.Black },
	L = { char = "L", fg = Colors.White, bg = Colors.Black },
	M = { char = "M", fg = Colors.White, bg = Colors.Black },
	N = { char = "N", fg = Colors.White, bg = Colors.Black },
	O = { char = "O", fg = Colors.White, bg = Colors.Black },
	P = { char = "P", fg = Colors.White, bg = Colors.Black },
	Q = { char = "Q", fg = Colors.White, bg = Colors.Black },
	R = { char = "R", fg = Colors.White, bg = Colors.Black },
	S = { char = "S", fg = Colors.White, bg = Colors.Black },
	T = { char = "T", fg = Colors.White, bg = Colors.Black },
	U = { char = "U", fg = Colors.White, bg = Colors.Black },
	V = { char = "V", fg = Colors.White, bg = Colors.Black },
	W = { char = "W", fg = Colors.White, bg = Colors.Black },
	X = { char = "X", fg = Colors.White, bg = Colors.Black },
	Y = { char = "Y", fg = Colors.White, bg = Colors.Black },
	Z = { char = "Z", fg = Colors.White, bg = Colors.Black },
	dot = { char = ".", fg = Colors.White, bg = Colors.Black },
	missing = { char = " ", fg = Colors.White, bg = Colors.Black },
}