
Glossary.Meta.Goblins = SpritePresentationMode("goblins-12x12.png", 12, 40)

Glossary.Goblins = {
	skel1 = { x = 13, y = 8, fg = Colors.Gray, bg = Colors.Black },
	skel2 = { x = 14, y = 8, fg = Colors.Gray, bg = Colors.Black },

	gob1 = { x = 15, y = 8, fg = Colors.White, bg = Colors.Black },
	gob2 = { x = 16, y = 8, fg = Colors.Green, bg = Colors.Black },

	kobold1 = { x = 25, y = 9, fg = Colors.White, bg = Colors.Black },
	kobold2 = { x = 26, y = 9, fg = Colors.Red, bg = Colors.Black },

	mage = { x = 20, y = 9, fg = Colors.Yellow, bg = Colors.Black },
	monk = { x = 21, y = 9, fg = Colors.Yellow, bg = Colors.Black },

	door_open = { x = 15, y = 16, fg = Colors.Gray, bg = Colors.Black },
	door_closed = { x = 16, y = 16, fg = Colors.Gray, bg = Colors.Black },

	back_dark = { x = 0, y = 0, fg = Colors.Gray, bg = Colors.Black },
	back_semi = { x = 6, y = 17, fg = Colors.Gray, bg = Colors.Black },
	back_mid = { x = 6, y = 16, fg = Colors.Gray, bg = Colors.Black },
	back_lit = { x = 5, y = 15, fg = Colors.Gray, bg = Colors.Black },

	back_old1 = { x = 6, y = 14, fg = Colors.Gray, bg = Colors.Black },
	back_old2 = { x = 7, y = 14, fg = Colors.Gray, bg = Colors.Black },
	back_old3 = { x = 8, y = 14, fg = Colors.Gray, bg = Colors.Black },
	
	a = { x = 29, y = 2, fg = Colors.White, bg = Colors.Black },
	b = { x = 30, y = 2, fg = Colors.White, bg = Colors.Black },
	c = { x = 31, y = 2, fg = Colors.White, bg = Colors.Black },
	d = { x = 32, y = 2, fg = Colors.White, bg = Colors.Black },
	e = { x = 33, y = 2, fg = Colors.White, bg = Colors.Black },
	f = { x = 34, y = 2, fg = Colors.White, bg = Colors.Black },
	g = { x = 35, y = 2, fg = Colors.White, bg = Colors.Black },
	h = { x = 36, y = 2, fg = Colors.White, bg = Colors.Black },
	i = { x = 37, y = 2, fg = Colors.White, bg = Colors.Black },
	j = { x = 38, y = 2, fg = Colors.White, bg = Colors.Black },
	k = { x = 39, y = 2, fg = Colors.White, bg = Colors.Black },
	l = { x = 29, y = 3, fg = Colors.White, bg = Colors.Black },
	m = { x = 30, y = 3, fg = Colors.White, bg = Colors.Black },
	n = { x = 31, y = 3, fg = Colors.White, bg = Colors.Black },
	o = { x = 32, y = 3, fg = Colors.White, bg = Colors.Black },
	p = { x = 33, y = 3, fg = Colors.White, bg = Colors.Black },
	q = { x = 34, y = 3, fg = Colors.White, bg = Colors.Black },
	r = { x = 35, y = 3, fg = Colors.White, bg = Colors.Black },
	s = { x = 36, y = 3, fg = Colors.White, bg = Colors.Black },
	t = { x = 37, y = 3, fg = Colors.White, bg = Colors.Black },
	u = { x = 38, y = 3, fg = Colors.White, bg = Colors.Black },
	v = { x = 39, y = 3, fg = Colors.White, bg = Colors.Black },
	w = { x = 29, y = 4, fg = Colors.White, bg = Colors.Black },
	x = { x = 30, y = 4, fg = Colors.White, bg = Colors.Black },
	y = { x = 31, y = 4, fg = Colors.White, bg = Colors.Black },
	z = { x = 32, y = 4, fg = Colors.White, bg = Colors.Black },
	A = { x = 29, y = 2, fg = Colors.White, bg = Colors.Black },
	B = { x = 30, y = 2, fg = Colors.White, bg = Colors.Black },
	C = { x = 31, y = 2, fg = Colors.White, bg = Colors.Black },
	D = { x = 32, y = 2, fg = Colors.White, bg = Colors.Black },
	E = { x = 33, y = 2, fg = Colors.White, bg = Colors.Black },
	F = { x = 34, y = 2, fg = Colors.White, bg = Colors.Black },
	G = { x = 35, y = 2, fg = Colors.White, bg = Colors.Black },
	H = { x = 36, y = 2, fg = Colors.White, bg = Colors.Black },
	I = { x = 37, y = 2, fg = Colors.White, bg = Colors.Black },
	J = { x = 38, y = 2, fg = Colors.White, bg = Colors.Black },
	K = { x = 39, y = 2, fg = Colors.White, bg = Colors.Black },
	L = { x = 29, y = 3, fg = Colors.White, bg = Colors.Black },
	M = { x = 30, y = 3, fg = Colors.White, bg = Colors.Black },
	N = { x = 31, y = 3, fg = Colors.White, bg = Colors.Black },
	O = { x = 32, y = 3, fg = Colors.White, bg = Colors.Black },
	P = { x = 33, y = 3, fg = Colors.White, bg = Colors.Black },
	Q = { x = 34, y = 3, fg = Colors.White, bg = Colors.Black },
	R = { x = 35, y = 3, fg = Colors.White, bg = Colors.Black },
	S = { x = 36, y = 3, fg = Colors.White, bg = Colors.Black },
	T = { x = 37, y = 3, fg = Colors.White, bg = Colors.Black },
	U = { x = 38, y = 3, fg = Colors.White, bg = Colors.Black },
	V = { x = 39, y = 3, fg = Colors.White, bg = Colors.Black },
	W = { x = 29, y = 4, fg = Colors.White, bg = Colors.Black },
	X = { x = 30, y = 4, fg = Colors.White, bg = Colors.Black },
	Y = { x = 31, y = 4, fg = Colors.White, bg = Colors.Black },
	Z = { x = 32, y = 4, fg = Colors.White, bg = Colors.Black },
	dot = { x = 6, y = 14, fg = Colors.Gray, bg = Colors.Black },
	missing = { x = 0, y = 0, fg = Colors.White, bg = Colors.Black },
}