
IncludeGameplay "DungeonEntities"
IncludeGameplay "Chances"
IncludeGameplay "UIRender"
IncludeGameplay "Wheels"
IncludeGameplay "DungeonMaker"
IncludeGameplay "BumpMechanics"
IncludeGameplay "ItemLibrary"
IncludeGameplay "ItemEffects"

LoadPlayerSystem "DefaultInputActions"
LoadPlayerSystem "InventoryInputActions"
LoadPlayerSystem "LootInputActions"
LoadPlayerSystem "InventoryUpdate"
LoadPlayerSystem "TargetingInputActions"

LoadEnviroSystem "FriendlySwapBehaviour"
LoadEnviroSystem "PassabilityUpdate"
LoadEnviroSystem "FireSpreadingMechanics"
LoadEnviroSystem "UpdateDistances"
LoadEnviroSystem "AIBehaviours"
LoadEnviroSystem "PlatformMechanics"
LoadEnviroSystem "HealingMechanics"
LoadEnviroSystem "OpenContainerMechanics"
LoadEnviroSystem "BumpAltarMechanics"
LoadEnviroSystem "LightFireSystem"
LoadEnviroSystem "HateMechanics"
LoadEnviroSystem "BumpAttackMechanics"
LoadEnviroSystem "DelayedDamageMechanics"
LoadEnviroSystem "StatusEffectUpdate"
LoadEnviroSystem "InflictStatusMechanics"
LoadEnviroSystem "PickUpMechanics"
LoadEnviroSystem "ShadowCastMechanics"
LoadEnviroSystem "ChallengeMechanics"
LoadEnviroSystem "ParalyzedResolveMechanics"
LoadEnviroSystem "TurnOrder"

LoadRenderSystem "DungeonRender"
LoadRenderSystem "PossibleMoveRender"
LoadRenderSystem "TopLevelRender"
LoadRenderSystem "VFXRender"
LoadRenderSystem "FadeOutRender"
LoadRenderSystem "PlayerBasedExplosion"
LoadRenderSystem "TimeoutCounterRender"
LoadRenderSystem "PlayerInfoRender"
LoadRenderSystem "TargetRender"
LoadRenderSystem "InventoryRender"
LoadRenderSystem "LootRender"
LoadRenderSystem "ScanScreenRender"
LoadRenderSystem "DiaryRender"
LoadRenderSystem "WinScreenRender"
LoadRenderSystem "DeathRender"

LoadScriptIfExists "debug\\DebugSpawnLibrary"
LoadScriptIfExists "debug\\render\\DebugDistancesRender"
LoadScriptIfExists "debug\\render\\DebugEntitySpawnRender"

World:Entity(MakeDungeonRequest)
Diary.Write("Welcome, brave sojourner.")