
IncludeGameplay "DungeonEntities"
IncludeGameplay "Chances"
IncludeGameplay "UIRender"
IncludeGameplay "Wheels"
IncludeGameplay "DungeonMaker"
IncludeGameplay "BumpMechanics"
IncludeGameplay "ItemLibrary"

LoadPlayerSystem "DefaultInputActions"
LoadPlayerSystem "InventoryInputActions"
LoadPlayerSystem "InventoryUpdate"
LoadPlayerSystem "TargetingInputActions"

LoadEnviroSystem "FriendlySwapBehaviour"
LoadEnviroSystem "PassabilityUpdate"
LoadEnviroSystem "FireSpreadingMechanics"
LoadEnviroSystem "AIBehaviours"
LoadEnviroSystem "TurnOrder"
LoadEnviroSystem "UpdateDistances"
LoadEnviroSystem "PlatformMechanics"
LoadEnviroSystem "HealingMechanics"
LoadEnviroSystem "BumpAttackMechanics"
LoadEnviroSystem "DelayedDamageMechanics"
LoadEnviroSystem "StatusEffectUpdate"
LoadEnviroSystem "InflictStatusMechanics"
LoadEnviroSystem "PickUpMechanics"
LoadEnviroSystem "ShadowCastMechanics"
LoadEnviroSystem "ChallengeMechanics"

LoadRenderSystem "DungeonRender"
LoadRenderSystem "PossibleMoveRender"
LoadRenderSystem "TopLevelRender"
LoadRenderSystem "VFXRender"
LoadRenderSystem "FadeOutRender"
LoadRenderSystem "PlayerBasedExplosion"
LoadRenderSystem "TimeoutCounterRender"
LoadRenderSystem "DiaryRender"
LoadRenderSystem "PlayerInfoRender"
LoadRenderSystem "TargetRender"
LoadRenderSystem "InventoryRender"

LoadScriptIfExists "debug\\DebugSpawnLibrary"
LoadScriptIfExists "debug\\render\\DebugDistancesRender"
LoadScriptIfExists "debug\\render\\DebugEntitySpawnRender"

World:Entity(MakeDungeonRequest)
Diary.Write("7DRL PANIC")