PCG:Clear()
PCG:LoadProcs("dungeon")

PCG:RunProc("start", 6)
PCG:RunProc("connect", 12)
PCG:RunProc("entry", 1)
PCG:RunProc("zone", 1)
PCG:RunProc("branch", 2)
PCG:RunProc("zone", 3)
PCG:RunProc("hard", 5)
PCG:RunProc("cleanup", 10)
PCG:RunProc("template", 10)
PCG:RunProc("secrets", 10)
PCG:RunProc("exit", 1)
PCG:RunProc("intro", 5)
PCG:RunProc("intronope", 5)

PCG:EmitDot()